skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
reputation = "AdJRTSZ9pBrgzHsKErZZUruRkqVG929zsUPNrJeo3dBM"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
